language: python
python:
- 3.5
- 3.6
services:
- rabbitmq
install:
- pip install -r requirements_dev.txt
- pip install --editable .
- pip freeze
env:
- AMQP_VHOST=test
before_script:
- sudo rabbitmq-plugins enable rabbitmq_management
- wget http://guest:guest@localhost:15672/cli/rabbitmqadmin -O rabbitmqadmin
- chmod +x rabbitmqadmin
- ./rabbitmqadmin declare user name=guest password=guest tags=administrator
script: make test
